name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What's wrong or missing in the documentation?
      placeholder: The README doesn't explain how to configure...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation (file path, URL, or section)?
      placeholder: "README.md, line 45" or "CONTRIBUTING.md, Development Setup section"

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Add a step-by-step guide with examples...

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Missing documentation
        - Incorrect information
        - Unclear or confusing
        - Outdated information
      default: 0

